server:
  port: 8887

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

zuul:
  routes:
    data-center:
      path: /v1/data/**
      url: http://localhost:8801/v1/data
    device-center:
      path: /v1/devices/**
      url: http://localhost:8806/v1/devices
    file:
      path: /v1/files/**
      url: http://localhost:8807/v1/files
    user:
      path: /v1/users/**
      url: http://localhost:8809/v1/users
    feedback:
      path: /v1/feedback/**
      url: http://localhost:8811/v1/feedback

user:
  service:
    uri: http://localhost:8809/

auth:
  ignored:
    rules:
      - host: localhost
        path: ^(/v1/users/verificationCodes)[a-z0-9\-/]*
        method: POST
      - host: localhost
        path: ^(/v1/users/signin)[a-z0-9\-/]*
        method: POST
      - host: localhost
        path: ^(/v1/users/signout)[a-z0-9\-/]*
        method: DELETE