server:
  port: 8889

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

zuul:
  ignoredPatterns: /data-definitions/**/verify, /data-definitions/verify, /data-definitions**
  routes:
    data-center:
      path: /data/**
      url: http://localhost:8801/data
    data-definition:
      path: /data-definitions/**
      url: http://localhost:8802/data-definitions
    developer-signin:
      path: /developers/signin
      url: http://localhost:8804/
      stripPrefix: true
    developer-signout:
      path: /developers/signout
      url: http://localhost:8804/
    developer-signup:
      path: /developers/signup
      url: http://localhost:8804/
    developer-open:
      path: /developers/open/**
      url: http://localhost:8804/developers/open
    developer-resource:
      path: /developers/resource/**
      url: http://localhost:8804/developers/resource
    device-definition:
      path: /device-definitions/**
      url: http://localhost:8805/device-definitions
    device-center:
      path: /devices/**
      url: http://localhost:8806/devices
    file:
      path: /files/**
      url: http://localhost:8807/files
    user:
      path: /users/**
      url: http://localhost:8809/users
    report:
      path: /reports/**
      url: http://localhost:8811/reports


user:
  service:
    uri: http://localhost:8809/v1/users/

auth:
  ignored:
    rules:
      - host: www.umasuo.com
        path: ^(/auth/anonymous)
        method: GET
      - host: localhost
        path: ^(/developers/signin)[a-z0-9\-/]*
        method: POST
      - host: localhost
        path: ^(/developers/signup)[a-z0-9\-/]*
        method: POST
      - host: localhost
        path: ^(/developers/signout)[a-z0-9\-/]*
        method: DELETE