kind: List
apiVersion: v1
items:
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    namespace: dev
    name: api-gateway
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: api-gateway
      spec:
        containers:
        - name: api-gateway
          image: reactivesw/api-gateway:0.1
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          env:
          - name: server_port
            value: "80"
          - name: spring_cloud_config_uri
            value: http://reactivesw-config
- kind: Service
  apiVersion: v1
  metadata:
    name: api-gateway
    namespace: dev
    labels:
      name: api-gateway
  spec:
    type: LoadBalancer
    ports:
    - port: 80
      nodePort: 30111
    selector:
      name: api-gateway